app.py, controllers/user_manager_page_controller.py, models/user.py, models/user_manager.py, services/user_manager_service.py, templates/base.html, templates/user_profile.html
Создана возможность создания пользователя.
А также исправлена кнопка выхода в боковом меню(Log out).
=> Возможность создания пользователя

.idea/cleverhealth_1.app.iml, app.py, controllers/user_manager_page_controller.py, data_adapters/data_store.py, models/user.py, models/user_manager.py, services/user_manager_service.py, templates/base.html, templates/user_profile.html
Теперь можно редактировать данные пользователей.
=> Change user

.idea/cleverhealth_1.app.iml, app.py, controllers/user_manager_page_controller.py, data_adapters/data_store.py, models/user.py, models/user_manager.py, services/user_manager_service.py, templates/base.html, templates/user_profile.html
Это ветка с создание и редактированием пользователя без недочетов
=> Add and change user

app.py, controllers/user_manager_page_controller.py, data_adapters/data_store.py, models/user.py, models/user_manager.py, services/user_manager_service.py, templates/user_profile.html
Добавлена возможность "Сброс пароля", а также баги связанные со сроком доступа.
=> Discharge password and fixed bags

app.py, models/action_manager.py, models/estimated_values_manager.py, models/probationer.py, models/probationer_manager.py, models/probe.py, models/probe_probationer.py, models/probes_manager.py, models/user_manager.py, services/action_service.py, services/estimated_values_service.py, services/probationer_card_service.py, services/probe_profile_service.py, services/user_profile_service.py, templates/estimated_values.html, templates/probe_profile.html, templates/protocols.html
-показ справочников оценочных значений для определенных возрастов
Добавлены:
- действие "добавление проб"
=> Испрвлены баги:

app.py, controllers/education_main_course_lesson_page_controller.py, controllers/education_main_course_page_controller.py, models/course.py, models/course_manager.py, services/course_service.py, templates/education_main_course.html, templates/education_main_courses_lesson.html
Пока переход на уроки не доделан.
=> Добавлена возможность просмотра списка уроков.

models/user_manager.py, templates/education_list_courses.html, templates/user_profile.html
"Список курсов"
"Карточка пользователя"
=> Исправлена мобильная версия страницы:

app.py, controllers/education_course_lesson_page_controller.py, controllers/user_profile_page_controller.py, data_adapters/data_store.py, models/room_chat.py, models/room_chat_manager.py, models/user.py, services/room_chat_service.py, services/user_manager_service.py, services/user_profile_service.py, templates/education_courses_lesson.html, templates/user_profile.html
Исправлен баг на странице "Карточка пользователя"
=> Добавлен чат на странице "Урок"

app.py, config.py, controllers/main_page_controller.py, controllers/probationer_card_page_controller.py, controllers/user_manager_page_controller.py, controllers/user_profile_page_controller.py, data_adapters/data_store.py, models/probationer_manager.py, models/user.py, models/user_manager.py, services/probationer_card_service.py, services/user_profile_service.py, static/js/nhc_utils.js, templates/estimated_values.html, templates/price_list.html, templates/probationer_card.html, templates/probes.html, templates/settings.html, templates/user_manager.html, templates/user_profile.html
Перенесены все настройки в config
Исправлены страница Настройки для мобильной версии
Добавлена функция продления срока доступа
=> Исправлены баги в карточке тестируемых

app.py, controllers/education_course_lesson_page_controller.py, controllers/education_course_page_controller.py, controllers/main_page_controller.py, models/action.py, models/action_manager.py, services/course_service.py, templates/education_course.html, templates/education_courses_lesson.html, templates/main_page.html, templates/user_manager.html
Изменена структура хранения действий пользователей
Добавлено логирование просмотра страницы с уроком
=> Изменен вывод ленты активностей на главном экране

app.py, controllers/education_course_lesson_page_controller.py, controllers/education_course_page_controller.py, controllers/user_manager_page_controller.py, models/course_manager.py, models/user_manager.py, templates/education_course.html, templates/education_courses_lesson.html, templates/user_manager.html
Изменен вывод списка уроков
Сделана проверка на доступ к уроку при переходите на страницу урока
=> Добавлен на странице со списком пользователей столбец "Доступ к центру обучения"

app.py, static/js/nhc_utils.js, templates/education_course.html, templates/education_courses_lesson.html, templates/user_manager.html
Исправлена проверка доступа к уроку при переходе по прямой ссылке
Исправлена запись действий пользователей
=> Исправлена страница со списком курсов

models/estimated_values_manager.py, templates/base.html, templates/probe_profile.html, templates/user_manager.html
Исправлен шрифт на странице "probe_profile"
Скрыты "Инструкция пользователя" и "Журнал изменений"
=> Исправлена таблица на странице со списком пользователей

app.py, templates/main_page.html, templates/user_manager.html
Исправлена внешнюю часть рабочего стола
Исправлен показ modal form(порой показывалась не там где надо)
Исправлены сообщения об сохранении изменений
Изменена таблица со списком пользователей
=> Дополнена проверку email на фронте

app.py, config.py
Изменено сообщение при успешном продлении доступа
=> Добавлено продление доступа на 2 месяца

app.py, controllers/main_page_controller.py, models/user_manager.py, services/user_manager_service.py, templates/main_page.html, templates/user_manager.html
Исправлена кнопка отмена про редактирование/создание пользователя
=> Добавлен "сменить пароль" на главную страницу

app.py, models/action_manager.py, services/action_service.py, services/course_service.py, services/estimated_values_service.py, services/probationer_card_service.py, services/probe_profile_service.py, services/user_manager_service.py, services/user_profile_service.py, static/js/nhc_utils.js, templates/main_page.html, templates/registration.html, templates/user_manager.html
Изменены соббщения об ошибке или успешном действии на страницах со списком пользователей, главной странице и регистрации
Изменена запись действий об изменении пароля, добавления пользователя, продления срока доступа и разблокировки/блокировки пользователя
Исправлена разблокировка/блокировка пользователя
=> Исправлена кнопка "Отмена" на странице со списком пользователей

controllers/main_page_controller.py, models/action_manager.py, models/course.py, models/probationer_manager.py, services/action_service.py, services/course_service.py, services/estimated_values_service.py, services/probationer_card_service.py, services/probe_profile_service.py, services/user_manager_service.py, services/user_profile_service.py, static/js/nhc_utils.js, templates/user_manager.html
Исправлен внешний вид страницы со списком пользователей
=> Исправлена запись действий пользователей

app.py, controllers/education_course_lesson_page_controller.py, controllers/education_course_page_controller.py, controllers/education_home_task_profile_page_controller.py, controllers/education_home_tasks_page_controller.py, models/room_chat_manager.py, services/education_course_service.py, services/homework_service.py, templates/education_course.html, templates/education_courses_lesson.html, templates/education_home_task_profile.html, templates/education_home_tasks.html, templates/room_chat.html
Изменены страницы с проверкой домашки, списком домашек, списком уроков
=> Чат перенесен в отдельный файл

controllers/education_home_tasks_page_controller.py, templates/education_home_tasks.html
=> Добавлен столбец Модуль

app.py, controllers/education_course_lesson_page_controller.py, controllers/education_home_task_profile_page_controller.py, controllers/education_home_tasks_page_controller.py, models/action_manager.py, models/homework_manager.py, services/download_service.py, services/education_course_service.py, services/estimated_values_service.py, services/homework_service.py, services/main_page_service.py, services/probationer_card_service.py, services/probe_profile_service.py, services/user_manager_service.py, services/user_profile_service.py, templates/education_courses_lesson.html, templates/education_home_task_profile.html, templates/user_manager.html
Отредактировано скачивание файлов
Добавлены события:
Сдано домашняя работа
Принята/не принята домашняя работа
Отредактированы события
Исправлена мобильная версия страницы проверки домашки
=> Изменено центрирования ФИО пользователей и email в списке пользователей

templates/education_courses_lesson.html
=> fixing Update education_courses_lesson.html

services/login_service.py, templates/education_courses_lesson.html, templates/education_home_tasks.html, templates/user_manager.html
Увеличено количество записей списков домашних заданий и пользователей на одной странице до 20
Если superuser заходит на страницу с уроком, то вместо чата появляется надпись "Чат не доступен"
=> Добавлена запись действия "Вход пользователя в систему"

config.py, controllers/education_course_page_controller.py, services/education_course_service.py
- Открыт 6 модуль 1 потока
- Исправлен контент курса
- Если урок просматривает суперпользователь, то вместо чата выводиться сообщение "чат не доступен"
- Исправлено форматирование страницы урока
- На странице со списком пользователей увеличено количество строк до 20 
- На странице со списком сданных домашних заданий увеличено количество строк до 20
- Добавлена регистрация события "вход пользователя в систему"
=> update for 1.1.8

services/education_course_lesson_service.py, services/homeworks_service.py
Удалены не нужные эксепшены
Исправлены доступы к модулям для потоков
=> Fix accesses

app.py, controllers/education_home_tasks_page_controller.py, models/homework_manager.py, models/lesson_manager.py, models/message_manager.py, services/education_course_lesson_service.py, services/education_course_service.py, services/homework_card_service.py, services/homeworks_service.py, templates/education_home_tasks.html
Добавлены кнопки для показа домашних работ(чаты без домашней работы, проверенные домашние работы, не проверенные домашние работы)
=> Добавлено временное решение долгой загрузки страницы со списком домашних работ и чатов

templates/education_home_tasks.html
Надпись "Не проверено" в столбце "Ответ" обведена тем же цветом, что и в столбце "Статус"
=> Исправлено отображение надписи "Не проверено" в столбце "Ответ"

app.py, controllers/education_course_lesson_page_controller.py, controllers/education_home_task_card_page_controller.py, controllers/education_stream_page_controller.py, models/education_stream.py, models/education_stream_manager.py, models/homework_manager.py, services/education_stream_service.py, templates/education_stream_card.html
Добавлена проверка на повторную сдачу домашней работы
Добавлена переадресация для того, чтобы повторно не отправлялись сообщения/домашние работы
=> Исправление повторного отправления домашней работы/сообщений

app.py, controllers/education_course_lesson_page_controller.py, controllers/education_home_task_card_page_controller.py, controllers/education_stream_page_controller.py, models/homework_manager.py, models/timetable.py, models/timetable_manager.py, services/education_course_lesson_service.py, services/education_stream_service.py, services/homework_card_service.py, templates/education_stream_card.html
Добавлены файлы timetable.py и timetable_manager.py
=> Добавлены недостающие файлы

app.py, controllers/education_home_tasks_page_controller.py, controllers/education_stream_page_controller.py, controllers/education_streams_page_controller.py, data_adapters/data_store.py, data_adapters/tinydb_data_adapter.py, models/education_stream_manager.py, models/timetable_manager.py, services/education_course_lesson_service.py, services/education_course_service.py, services/education_list_courses_service.py, services/education_stream_service.py, services/education_streams_service.py, services/homeworks_service.py, templates/education_home_tasks.html, templates/education_stream_card.html, templates/education_streams.html
Исправлено создание/просмотр/редактирование обучающего потока
Добавлена возможность редактировать расписания потока
=> Исправлен обучающий поток

app.py, controllers/education_stream_page_controller.py, templates/education_stream_card.html
Исправлено создание/редактирование обучающего потока
Добавлено уведомление об успешном создании/редактирование обучающего потока
=> Исправлены потоки и добавлены уведомления

app.py, controllers/user_profile_page_controller.py, models/user_manager.py, services/user_profile_service.py, templates/education_stream_card.html, templates/user_profile.html
"Сброс пароля" и "Продление подписки" перенесены на выпадающее окно на странице "Профиль пользователя"
Исправлен внешний вид таблиц "Обучающие потоки" на странице "Профиль пользователя" и "Доступные модули" на странице "Карточка обучающего потока"
=> Изменены внешний вид страниц "Профиль пользователя" и "Карточка обучающего потока"

app.py, controllers/education_stream_page_controller.py, controllers/main_page_controller.py, models/action_manager.py, models/education_stream_manager.py, models/user_manager.py, services/education_stream_service.py, static/img/icons/no-view.svg, static/img/icons/view.svg, static/js/nhc_utils.js, templates/base.html, templates/education_home_task_card.html, templates/education_stream_card.html, templates/education_streams.html, templates/main_page.html, templates/registration.html, templates/user_profile.html
Исправлена проверка на клиенте при регистрации/создании/редактирование пользователя
Добавлен столбец "Email" в таблицы "Ученики" и "Кураторы" на странице "Карточка обучающего потока"
Удален столбец "#" и изменены размеры столбцов на странице "Список обучающих потоков"
Добавлена возможность просматривания пароля при регистрации пользователя на странице "Регистрация", при сбросе пароля на странице "Рабочий стол", при создании/редактирование пользователя на странице "Профиль пользователя"
Добавлены запись действий "Создание/Редактирование обучающего потока"
Изменен внешний вид значений в столбце "Статус" на странице "Список обучающих потоков"
Добавлена проверка текущего пароля пользователя на странице "Рабочий стол"
Добавлена проверка выбора ответа на домашнее задание на странице "Проверка …
=> Изменения на страницах "Профиль пользователя", "Рабочий стол", "Карточка обучающего потока", "Список обучающих потоков", "Проверка домашнего задания"

app.py, controllers/education_list_courses_page_controller.py, services/education_list_courses_service.py, templates/education_list_courses.html
Добавлена возможность просмотра прогресса обучения текущего пользователя
=> Дополнение страницы "Список курсов"

app.py, controllers/education_home_tasks_page_controller.py, models/homework_manager.py, models/message_manager.py, services/homeworks_service.py, templates/education_home_tasks.html, templates/user_actions.html
Изменен внешний вид страницы, теперь:
-Справа отображается select с обучающими потоками. При выборе потока из списка, перезагружается страница и отображает ниже таблицу с пользователями данного потока
-Таблица с пользователями состоит из колонок: имя пользователя, домашние работы(сколько принято/не принято), новые сообщения. При нажатии на имя пользователя, перезагружается страница и отображается справа таблицу с его домашними заданиями
-Слева отображается название курса, по которому поток обучается. Ниже написано имя пользователя, которого выбрали из таблицы слева.
-Над таблицей находятся фильтры по домашних работам выбранного пользователя.
-Ниже находится сама таблица с домашними работами(колонки используется те же, что и раньше)
=> Изменение страницы со списком домашних заданий

app.py, controllers/education_home_tasks_page_controller.py, controllers/user_profile_page_controller.py, services/user_profile_service.py, templates/education_home_tasks.html, templates/user_profile.html
Изменения на странице "Профиль пользователя":
-В таблице со списком обучающих потоков, добавлен столбец с ролью данного пользователя в потоке
Изменения на странице "Проверка домашних работ":
-Увеличено расстояние между таблицами
-Выделяется активная строка с пользователем
-Поток и список учеников разделенные на 2 блока
-При переходе на страницу/смене потока первый в списке ученик уже выбран
=> Education stream correction

templates/education_home_tasks.html
Выровнены таблицы в мобильной версии
Названия модулей больше не вылезают за рамки в таблице со списком домашних работ в мобильной версии Выровнены фильтры в мобильной версии
Выровнены названия столбцов со списком пользователей в мобильной версии
=> Изменения страницы со списком домашних работ в мобильной версии

templates/education_home_tasks.html
Убрана библиотека Choices.js
Изменен вид фильтров для домашних работ (чек-боксы на выпадающий список)
=> Добавлены отступы и сделаны везде одинаковыми

app.py, services/education_course_lesson_service.py
Исправлен баг с выбором потока без пользователей(студентов)
=> Исправлен баг с переходами на соседние уроки

app.py, templates/education_home_tasks.html
Название урока в таблице с домашними работами теперь является ссылкой с возможностью выполнения домашней работы в новом окне или в этом же
=> Изменения на странице "Проверка домашнего задания"

data_adapters/data_store.py, models/action_manager.py, models/user_manager.py, services/maintenance_service.py, templates/maintenance.html
Исправлено создание действий пользователя
Исправлен вход в систему
=> Change user store

app.py, controllers/education_home_tasks_page_controller.py, controllers/education_stream_page_controller.py, controllers/user_manager_page_controller.py, models/homework_manager.py, models/user_manager.py, services/education_stream_card_service.py, services/homeworks_service.py, services/maintenance_service.py, services/user_manager_service.py, templates/education_home_tasks.html, templates/user_manager.html
Изменена логика обработки данных пользователей для ускорения обработки запросов на страницах:
-  Список пользователей
- Список домашних работ
- Карточка обучающего потока
=> Изменения логики
